from typing import Dict, Any

VEDIC_ONTOLOGY: Dict[str, Any] = {
    "DEITIES": {
        "TRIAD": {
            "BRAHMA": {
                "id": "deity:brahma",
                "type": "Deity",
                "name": "Brahma",
                "sanskrit_name": "ब्रह्मा",
                "domain": "Creator",
                "attributes": {
                    "role": "Creation principle",
                    "vehicles": "Swan (Hamsa)",
                    "color": "Red",
                    "form": "4 faces, 4 arms",
                },
            },
            "VISHNU": {
                "id": "deity:vishnu",
                "type": "Deity",
                "name": "Vishnu",
                "sanskrit_name": "विष्णु",
                "domain": "Preserver",
                "attributes": {
                    "role": "Preservation principle",
                    "vehicles": "Eagle (Garuda)",
                    "color": "Blue",
                    "avatar_count": 10,
                },
            },
            "SHIVA": {
                "id": "deity:shiva",
                "type": "Deity",
                "name": "Shiva",
                "sanskrit_name": "शिव",
                "domain": "Destroyer/Transformer",
                "attributes": {
                    "role": "Transformation principle",
                    "vehicles": "Bull (Nandi)",
                    "color": "White",
                    "form": "5 faces",
                },
            },
        },
        "AVATARS_OF_VISHNU": {
            "RAMA": {
                "id": "character:rama",
                "type": "Character",
                "name": "Rama",
                "sanskrit_name": "राम",
                "parent_entity": "deity:vishnu",
                "relation_types": ["MANIFESTS_AS"],
                "characteristics": ["righteous", "dutiful", "perfect_human"],
                "text_references": ["Ramayana"],
            },
            "KRISHNA": {
                "id": "character:krishna",
                "type": "Character",
                "name": "Krishna",
                "sanskrit_name": "कृष्ण",
                "parent_entity": "deity:vishnu",
                "relation_types": ["MANIFESTS_AS"],
                "characteristics": ["divine", "teacher", "lover"],
                "text_references": ["Bhagavad Gita", "Bhagavata Purana"],
            },
        },
        "DIVINE_BEINGS": {
            "INDRA": {
                "id": "deity:indra",
                "type": "Deity",
                "name": "Indra",
                "domain": "King of Gods",
            },
            "AGNI": {
                "id": "deity:agni",
                "type": "Deity",
                "name": "Agni",
                "domain": "Fire",
            },
            "SURYA": {
                "id": "deity:surya",
                "type": "Deity",
                "name": "Surya",
                "domain": "Sun",
            },
            "VAYU": {
                "id": "deity:vayu",
                "type": "Deity",
                "name": "Vayu",
                "domain": "Wind",
            },
        },
    },
    "CONCEPTS": {
        "FUNDAMENTAL": {
            "BRAHMAN": {
                "id": "concept:brahman",
                "type": "Concept",
                "name": "Brahman",
                "sanskrit_name": "ब्रह्मन्",
                "definition": "Ultimate reality, absolute consciousness",
                "subcategories": ["non-dual", "infinite", "eternal"],
            },
            "ATMAN": {
                "id": "concept:atman",
                "type": "Concept",
                "name": "Atman",
                "sanskrit_name": "आत्मन्",
                "definition": "Individual soul, self",
                "relations": ["IS_ASPECT_OF:concept:brahman"],
            },
            "MAYA": {
                "id": "concept:maya",
                "type": "Concept",
                "name": "Maya",
                "sanskrit_name": "माया",
                "definition": "Illusion, the power of manifestation",
                "subcategories": ["ignorance", "creative_power"],
            },
        },
        "DHARMA": {
            "id": "concept:dharma",
            "type": "Concept",
            "name": "Dharma",
            "sanskrit_name": "धर्म",
            "definition": "Righteous duty, cosmic order",
            "subcategories": [
                "sanatana-dharma",
                "varna-dharma",
                "ashrama-dharma",
                "sva-dharma",
            ],
        },
        "KARMA": {
            "id": "concept:karma",
            "type": "Concept",
            "name": "Karma",
            "sanskrit_name": "कर्म",
            "definition": "Action and its consequences",
            "subcategories": ["karma-yoga", "karma-phala", "karma-siddhanta"],
        },
        "YOGA_PATHS": {
            "BHAKTI": {
                "id": "concept:bhakti_yoga",
                "type": "Concept",
                "name": "Bhakti Yoga",
                "definition": "Path of devotion",
                "components": ["love", "surrender", "faith"],
            },
            "KARMA_YOGA": {
                "id": "concept:karma_yoga",
                "type": "Concept",
                "name": "Karma Yoga",
                "definition": "Path of righteous action",
                "components": ["duty", "non-attachment", "service"],
            },
            "JNANA": {
                "id": "concept:jnana_yoga",
                "type": "Concept",
                "name": "Jnana Yoga",
                "definition": "Path of knowledge",
                "components": ["wisdom", "discrimination", "inquiry"],
            },
            "RAJA": {
                "id": "concept:raja_yoga",
                "type": "Concept",
                "name": "Raja Yoga",
                "definition": "Path of meditation",
                "components": ["mental discipline", "focus", "enlightenment"],
            },
        },
        "LIBERATION": {
            "id": "concept:moksha",
            "type": "Concept",
            "name": "Moksha",
            "sanskrit_name": "मोक्ष",
            "definition": "Liberation from cycle of birth and death",
            "synonyms": ["nirvana", "kaivalya", "samadhi"],
        },
    },
    "CHARACTERS": {
        "RAMAYANA": {
            "RAMA": {
                "id": "character:rama",
                "type": "Character",
                "name": "Rama",
                "role": "protagonist",
                "nature": "avatar",
            },
            "SITA": {
                "id": "character:sita",
                "type": "Character",
                "name": "Sita",
                "role": "heroine",
                "nature": "divine",
            },
            "LAKSHMAN": {
                "id": "character:lakshman",
                "type": "Character",
                "name": "Lakshman",
                "role": "brother",
                "nature": "devoted",
            },
            "HANUMAN": {
                "id": "character:hanuman",
                "type": "Character",
                "name": "Hanuman",
                "role": "devotee",
                "nature": "vanara",
            },
            "RAVANA": {
                "id": "character:ravana",
                "type": "Character",
                "name": "Ravana",
                "role": "antagonist",
                "nature": "demon_king",
            },
        },
        "MAHABHARATA": {
            "ARJUNA": {
                "id": "character:arjuna",
                "type": "Character",
                "name": "Arjuna",
                "role": "hero",
                "nature": "warrior_prince",
            },
            "KRISHNA": {
                "id": "character:krishna",
                "type": "Character",
                "name": "Krishna",
                "role": "guide",
                "nature": "avatar",
            },
            "YUDHISHTHIRA": {
                "id": "character:yudhishthira",
                "type": "Character",
                "name": "Yudhishthira",
                "role": "elder",
                "nature": "righteous",
            },
            "BHIMA": {
                "id": "character:bhima",
                "type": "Character",
                "name": "Bhima",
                "role": "strong",
                "nature": "warrior",
            },
            "DRAUPADI": {
                "id": "character:draupadi",
                "type": "Character",
                "name": "Draupadi",
                "role": "queen",
                "nature": "symbol_of_justice",
            },
            "DURYODHANA": {
                "id": "character:duryodhana",
                "type": "Character",
                "name": "Duryodhana",
                "role": "antagonist",
                "nature": "ambitious",
            },
            "KARNA": {
                "id": "character:karna",
                "type": "Character",
                "name": "Karna",
                "role": "tragic",
                "nature": "loyal",
            },
        },
    },
    "LOCATIONS": {
        "AYODHYA": {
            "id": "location:ayodhya",
            "type": "Location",
            "name": "Ayodhya",
            "sanskrit_name": "अयोध्या",
            "significance": "Capital of Ram's kingdom",
        },
        "KURUKSHETRA": {
            "id": "location:kurukshetra",
            "type": "Location",
            "name": "Kurukshetra",
            "sanskrit_name": "कुरुक्षेत्र",
            "significance": "Battlefield of Mahabharata",
        },
        "LANKA": {
            "id": "location:lanka",
            "type": "Location",
            "name": "Lanka",
            "sanskrit_name": "लंका",
            "significance": "Island kingdom of Ravana",
        },
        "VRINDAVAN": {
            "id": "location:vrindavan",
            "type": "Location",
            "name": "Vrindavan",
            "sanskrit_name": "वृंदावन",
            "significance": "Krishna's childhood home",
        },
    },
}
